import type {
  ActionCategory,
  ActionParameters,
  ActionTarget,
} from "./types.js";

export interface ActionTypeContract {
  readonly actionType: string;
  readonly category: ActionCategory;
  readonly allowedTargetKinds: readonly ActionTarget["kind"][];
  readonly parameterKind: ActionParameters["kind"];
}

export const CORE_ACTION_TYPE_CONTRACTS: readonly ActionTypeContract[] = [
  {
    actionType: "advertising.adjust_budget",
    category: "advertising",
    allowedTargetKinds: [
      "advertising_channel",
      "advertising_account",
      "campaign",
      "campaign_group",
      "ad_set",
      "ad_group",
      "audience",
      "product",
      "sku",
      "category",
      "collection",
      "product_group",
    ],
    parameterKind: "budget_adjustment",
  },
  {
    actionType: "advertising.adjust_spend_cap",
    category: "advertising",
    allowedTargetKinds: [
      "advertising_channel",
      "advertising_account",
      "campaign",
      "campaign_group",
      "ad_set",
      "ad_group",
      "audience",
      "product",
      "sku",
      "category",
      "collection",
      "product_group",
    ],
    parameterKind: "spend_cap_adjustment",
  },
  {
    actionType: "advertising.set_delivery_state",
    category: "advertising",
    allowedTargetKinds: [
      "advertising_channel",
      "advertising_account",
      "campaign",
      "campaign_group",
      "ad_set",
      "ad_group",
      "ad",
      "creative",
      "audience",
      "product",
      "sku",
      "category",
      "collection",
      "product_group",
    ],
    parameterKind: "paid_media_delivery",
  },
  {
    actionType: "advertising.set_allocation",
    category: "advertising",
    allowedTargetKinds: [
      "advertising_channel",
      "advertising_account",
      "campaign_group",
      "campaign",
    ],
    parameterKind: "paid_media_allocation",
  },
  {
    actionType: "advertising.transfer_budget_leg",
    category: "advertising",
    allowedTargetKinds: [
      "advertising_channel",
      "advertising_account",
      "campaign",
      "campaign_group",
      "ad_set",
      "ad_group",
      "audience",
      "product",
      "sku",
      "category",
      "collection",
      "product_group",
    ],
    parameterKind: "paid_media_transfer_leg",
  },
  {
    actionType: "advertising.pause_campaign",
    category: "advertising",
    allowedTargetKinds: ["campaign"],
    parameterKind: "toggle",
  },
  {
    actionType: "pricing.adjust_price",
    category: "pricing",
    allowedTargetKinds: ["sku", "product", "category", "collection"],
    parameterKind: "price_adjustment",
  },
  {
    actionType: "pricing.rollback_price",
    category: "pricing",
    allowedTargetKinds: ["sku", "product", "category", "collection"],
    parameterKind: "price_rollback",
  },
  {
    actionType: "promotion.apply_discount",
    category: "promotion",
    allowedTargetKinds: ["product", "sku", "category", "collection"],
    parameterKind: "promotion",
  },
  {
    actionType: "promotion.start",
    category: "promotion",
    allowedTargetKinds: ["promotion"],
    parameterKind: "promotion_start",
  },
  {
    actionType: "promotion.stop",
    category: "promotion",
    allowedTargetKinds: ["promotion"],
    parameterKind: "promotion_stop",
  },
  {
    actionType: "promotion.modify",
    category: "promotion",
    allowedTargetKinds: ["promotion"],
    parameterKind: "promotion_modify",
  },
  {
    actionType: "shipping.change_policy",
    category: "shipping",
    allowedTargetKinds: ["shipping_policy", "merchant"],
    parameterKind: "shipping_policy",
  },
  {
    actionType: "shipping.set_offer",
    category: "shipping",
    allowedTargetKinds: ["shipping_offer"],
    parameterKind: "shipping_offer_set",
  },
  {
    actionType: "shipping.modify_offer",
    category: "shipping",
    allowedTargetKinds: ["shipping_offer"],
    parameterKind: "shipping_offer_modify",
  },
  {
    actionType: "shipping.stop_offer",
    category: "shipping",
    allowedTargetKinds: ["shipping_offer"],
    parameterKind: "shipping_offer_stop",
  },
  {
    actionType: "shipping.adjust_policy",
    category: "shipping",
    allowedTargetKinds: ["shipping_policy"],
    parameterKind: "shipping_policy_adjustment",
  },
  {
    actionType: "shipping.rollback_policy",
    category: "shipping",
    allowedTargetKinds: ["shipping_policy"],
    parameterKind: "shipping_policy_rollback",
  },
  {
    actionType: "merchandising.move_product",
    category: "merchandising",
    allowedTargetKinds: ["collection", "product"],
    parameterKind: "merchandising_position",
  },
  {
    actionType: "merchandising.feature",
    category: "merchandising",
    allowedTargetKinds: ["sku", "product", "collection"],
    parameterKind: "merchandising_visibility",
  },
  {
    actionType: "merchandising.deprioritize",
    category: "merchandising",
    allowedTargetKinds: ["sku", "product", "collection"],
    parameterKind: "merchandising_visibility",
  },
  {
    actionType: "merchandising.set_rank",
    category: "merchandising",
    allowedTargetKinds: ["sku", "product", "collection"],
    parameterKind: "merchandising_rank",
  },
  {
    actionType: "merchandising.promote_substitute",
    category: "merchandising",
    allowedTargetKinds: ["merchandising_relationship"],
    parameterKind: "merchandising_relationship",
  },
  {
    actionType: "merchandising.set_cross_sell",
    category: "merchandising",
    allowedTargetKinds: ["merchandising_relationship"],
    parameterKind: "merchandising_relationship",
  },
  {
    actionType: "merchandising.set_upsell",
    category: "merchandising",
    allowedTargetKinds: ["merchandising_relationship"],
    parameterKind: "merchandising_relationship",
  },
  {
    actionType: "merchandising.remove_placement",
    category: "merchandising",
    allowedTargetKinds: ["merchandising_placement"],
    parameterKind: "merchandising_remove_placement",
  },
  {
    actionType: "merchandising.remove_relationship",
    category: "merchandising",
    allowedTargetKinds: ["merchandising_relationship"],
    parameterKind: "merchandising_remove_relationship",
  },
  {
    actionType: "merchandising.rollback_rank",
    category: "merchandising",
    allowedTargetKinds: ["sku", "product", "collection"],
    parameterKind: "merchandising_rank_rollback",
  },
  {
    actionType: "inventory.adjust_policy",
    category: "inventory",
    allowedTargetKinds: ["inventory_policy", "sku"],
    parameterKind: "inventory",
  },
  {
    actionType: "inventory.reorder",
    category: "inventory",
    allowedTargetKinds: ["sku"],
    parameterKind: "inventory_reorder",
  },
  {
    actionType: "inventory.adjust_reorder_quantity",
    category: "inventory",
    allowedTargetKinds: ["sku", "inventory_policy"],
    parameterKind: "inventory_reorder_quantity",
  },
  {
    actionType: "inventory.adjust_reorder_timing",
    category: "inventory",
    allowedTargetKinds: ["sku", "inventory_policy"],
    parameterKind: "inventory_reorder_timing",
  },
  {
    actionType: "inventory.set_safety_stock",
    category: "inventory",
    allowedTargetKinds: ["sku", "inventory_policy"],
    parameterKind: "inventory_policy_control",
  },
  {
    actionType: "inventory.set_reorder_point",
    category: "inventory",
    allowedTargetKinds: ["sku", "inventory_policy"],
    parameterKind: "inventory_policy_control",
  },
  {
    actionType: "inventory.protect_inventory",
    category: "inventory",
    allowedTargetKinds: ["sku", "product", "category", "collection", "inventory_set", "inventory_location"],
    parameterKind: "inventory_protection",
  },
  {
    actionType: "inventory.set_backorder_policy",
    category: "inventory",
    allowedTargetKinds: ["sku", "product", "inventory_policy"],
    parameterKind: "inventory_backorder_policy",
  },
  {
    actionType: "inventory.clearance",
    category: "inventory",
    allowedTargetKinds: ["sku", "product", "category", "collection", "inventory_set"],
    parameterKind: "inventory_clearance",
  },
  {
    actionType: "inventory.accelerate_excess_stock",
    category: "inventory",
    allowedTargetKinds: ["sku", "product", "category", "collection", "inventory_set"],
    parameterKind: "inventory_acceleration",
  },
  {
    actionType: "inventory.rollback_policy",
    category: "inventory",
    allowedTargetKinds: ["sku", "product", "inventory_policy"],
    parameterKind: "inventory_policy_rollback",
  },
  {
    actionType: "cro.change_page",
    category: "cro",
    allowedTargetKinds: ["page", "funnel_stage"],
    parameterKind: "page_change",
  },
  {
    actionType: "cro.modify_experience",
    category: "cro",
    allowedTargetKinds: ["cro_experience"],
    parameterKind: "cro_intervention",
  },
  {
    actionType: "cro.add_element",
    category: "cro",
    allowedTargetKinds: ["cro_experience"],
    parameterKind: "cro_intervention",
  },
  {
    actionType: "cro.remove_element",
    category: "cro",
    allowedTargetKinds: ["cro_experience"],
    parameterKind: "cro_intervention",
  },
  {
    actionType: "cro.reorder_elements",
    category: "cro",
    allowedTargetKinds: ["cro_experience"],
    parameterKind: "cro_intervention",
  },
  {
    actionType: "cro.modify_interaction",
    category: "cro",
    allowedTargetKinds: ["cro_experience"],
    parameterKind: "cro_intervention",
  },
  {
    actionType: "cro.modify_navigation",
    category: "cro",
    allowedTargetKinds: ["cro_experience"],
    parameterKind: "cro_intervention",
  },
  {
    actionType: "cro.modify_search",
    category: "cro",
    allowedTargetKinds: ["cro_experience"],
    parameterKind: "cro_intervention",
  },
  {
    actionType: "cro.modify_checkout",
    category: "cro",
    allowedTargetKinds: ["cro_experience"],
    parameterKind: "cro_intervention",
  },
  {
    actionType: "cro.rollback_experience",
    category: "cro",
    allowedTargetKinds: ["cro_experience"],
    parameterKind: "cro_rollback",
  },
  {
    actionType: "lifecycle.send",
    category: "lifecycle",
    allowedTargetKinds: ["lifecycle_program"],
    parameterKind: "lifecycle_send",
  },
  {
    actionType: "lifecycle.start_flow",
    category: "lifecycle",
    allowedTargetKinds: ["lifecycle_flow"],
    parameterKind: "lifecycle_flow_start",
  },
  {
    actionType: "lifecycle.stop_flow",
    category: "lifecycle",
    allowedTargetKinds: ["lifecycle_flow"],
    parameterKind: "lifecycle_flow_stop",
  },
  {
    actionType: "lifecycle.modify_flow",
    category: "lifecycle",
    allowedTargetKinds: ["lifecycle_flow"],
    parameterKind: "lifecycle_flow_modify",
  },
  {
    actionType: "lifecycle.adjust_frequency",
    category: "lifecycle",
    allowedTargetKinds: ["lifecycle_program", "customer_segment", "lifecycle_contact_policy"],
    parameterKind: "frequency_adjustment",
  },
  {
    actionType: "lifecycle.target_segment",
    category: "lifecycle",
    allowedTargetKinds: ["lifecycle_program", "lifecycle_flow"],
    parameterKind: "lifecycle_targeting",
  },
  {
    actionType: "lifecycle.rollback_policy",
    category: "lifecycle",
    allowedTargetKinds: ["lifecycle_contact_policy"],
    parameterKind: "lifecycle_policy_rollback",
  },
  {
    actionType: "customer_targeting.set_segment",
    category: "customer_targeting",
    allowedTargetKinds: ["customer_segment", "audience"],
    parameterKind: "segment_targeting",
  },
  {
    actionType: "experimentation.run_experiment",
    category: "experimentation",
    allowedTargetKinds: ["experiment"],
    parameterKind: "run_experiment",
  },
  {
    actionType: "investigation.inspect",
    category: "investigation",
    allowedTargetKinds: ["merchant", "funnel_stage", "page", "advertising_channel"],
    parameterKind: "investigate",
  },
  {
    actionType: "operational.change_setting",
    category: "operational",
    allowedTargetKinds: ["merchant", "inventory_policy", "shipping_policy"],
    parameterKind: "toggle",
  },
  {
    actionType: "no_op.do_nothing",
    category: "no_op",
    allowedTargetKinds: ["merchant"],
    parameterKind: "no_op",
  },
  {
    actionType: "no_op.wait_observe",
    category: "no_op",
    allowedTargetKinds: ["merchant", "advertising_channel", "campaign", "product", "sku"],
    parameterKind: "wait_observe",
  },
] as const;

export const CORE_CONSTRAINT_PROPERTIES = [
  "budget.available_minor",
  "budget.channel_available_minor",
  "price.floor_minor",
  "promotion.maximum_discount_rate",
  "inventory.available_units",
  "inventory.on_hand_units",
  "inventory.available_to_sell_units",
  "inventory.reserved_units",
  "inventory.safety_stock_units",
  "inventory.reorder_point_units",
  "inventory.open_purchase_order_units",
  "inventory.days_of_supply",
  "supplier.available_units",
  "supplier.minimum_order_quantity",
  "supplier.order_multiple",
  "warehouse.available_capacity_units",
  "inventory.sellable_units",
  "inventory.stock_coverage_days",
  "channel.exists",
  "campaign.exists",
  "product.exists",
  "product.active",
  "sku.exists",
  "experiment.eligible_traffic_sessions",
  "experiment.infrastructure_available",
  "lifecycle.audience_exists",
  "lifecycle.email_consent_eligible",
  "lifecycle.sms_consent_eligible",
  "lifecycle.valid_contact_destination",
  "lifecycle.channel_suppressed",
  "lifecycle.days_since_last_purchase",
  "lifecycle.days_since_last_engagement",
  "lifecycle.purchase_count",
  "lifecycle.contacts_in_window",
  "lifecycle.hours_since_last_contact",
  "shipping.backorders_supported",
  "finance.gross_margin_rate",
  "finance.gross_margin_per_unit_minor",
  "finance.contribution_margin_rate",
  "finance.contribution_per_unit_minor",
  "finance.gross_margin_rate_after_promotion",
  "finance.gross_margin_per_unit_after_promotion_minor",
  "finance.contribution_margin_rate_after_promotion",
  "finance.contribution_per_unit_after_promotion_minor",
  "finance.contribution_per_order_after_shipping_minor",
  "finance.contribution_margin_rate_after_shipping",
  "finance.gross_margin_rate_after_shipping",
  "shipping.merchant_cost_per_order_minor",
  "shipping.customer_charge_minor",
  "paid_media.total_budget_rate",
  "paid_media.channel_budget_rate",
  "paid_media.portfolio_budget_rate",
  "paid_media.classification_known",
  "operations.fulfillment_capacity_units_per_day",
  "data.measurement_available",
] as const;

export function getCoreActionTypeContract(
  actionType: string,
): ActionTypeContract | undefined {
  return CORE_ACTION_TYPE_CONTRACTS.find(
    (contract) => contract.actionType === actionType,
  );
}
