import type {
  AovProfile,
  CatalogProfile,
  CustomerEconomicsProfile,
  InventoryProfile,
  MarketingChannel,
  MarketingDependenceProfile,
  MerchantArchetype,
  PromotionProfile,
  PurchaseFrequencyProfile,
  SeasonalityProfile,
} from "./config.js";

export interface NumericRange {
  readonly min: number;
  readonly max: number;
}

export interface ArchetypeTendencies {
  readonly aovMinor: NumericRange;
  readonly grossMarginRate: NumericRange;
  readonly repeatProbability: NumericRange;
  readonly purchaseIntervalDays: NumericRange;
  readonly unitsPerOrder: NumericRange;
  readonly returnRate: NumericRange;
  readonly shippingSubsidyRate: NumericRange;
  readonly paymentFeeRate: NumericRange;
  readonly fulfillmentRate: NumericRange;
  readonly baselineConversionRate: NumericRange;
  readonly considerationDays: NumericRange;
  readonly brandStrength: NumericRange;
  readonly organicStrength: NumericRange;
  readonly visualAffinity: number;
  readonly searchIntent: number;
  readonly lifecycleAffinity: number;
  readonly priceSensitivity: NumericRange;
  readonly inventoryLeadDays: NumericRange;
  readonly inventoryDepthOrders: NumericRange;
  readonly catalogSkuRange: readonly [number, number];
  readonly channelSuitability: Readonly<Record<MarketingChannel, number>>;
  readonly aovBias: Readonly<Partial<Record<AovProfile, number>>>;
  readonly frequencyBias: Readonly<
    Partial<Record<PurchaseFrequencyProfile, number>>
  >;
  readonly marketingBias: Readonly<
    Partial<Record<MarketingDependenceProfile, number>>
  >;
  readonly promotionBias: Readonly<
    Partial<Record<PromotionProfile, number>>
  >;
  readonly catalogBias: Readonly<Partial<Record<CatalogProfile, number>>>;
  readonly inventoryBias: Readonly<Partial<Record<InventoryProfile, number>>>;
  readonly customerEconomicsBias: Readonly<
    Partial<Record<CustomerEconomicsProfile, number>>
  >;
  readonly seasonalityBias: Readonly<
    Partial<Record<SeasonalityProfile, number>>
  >;
}

const channels = (
  overrides: Partial<Record<MarketingChannel, number>>,
): Readonly<Record<MarketingChannel, number>> => ({
  meta: 0.5,
  google_search: 0.5,
  google_shopping: 0.5,
  pinterest: 0.3,
  email: 0.5,
  sms: 0.25,
  affiliate: 0.25,
  ...overrides,
});

export const ARCHETYPE_TENDENCIES: Readonly<
  Record<MerchantArchetype, ArchetypeTendencies>
> = {
  fashion_apparel: {
    aovMinor: { min: 6500, max: 22000 },
    grossMarginRate: { min: 0.48, max: 0.72 },
    repeatProbability: { min: 0.22, max: 0.55 },
    purchaseIntervalDays: { min: 45, max: 150 },
    unitsPerOrder: { min: 1.2, max: 2.6 },
    returnRate: { min: 0.08, max: 0.28 },
    shippingSubsidyRate: { min: 0.02, max: 0.08 },
    paymentFeeRate: { min: 0.022, max: 0.036 },
    fulfillmentRate: { min: 0.035, max: 0.09 },
    baselineConversionRate: { min: 0.012, max: 0.045 },
    considerationDays: { min: 1, max: 12 },
    brandStrength: { min: 0.08, max: 0.5 },
    organicStrength: { min: 0.12, max: 0.48 },
    visualAffinity: 0.9,
    searchIntent: 0.55,
    lifecycleAffinity: 0.72,
    priceSensitivity: { min: -2.1, max: -0.7 },
    inventoryLeadDays: { min: 20, max: 120 },
    inventoryDepthOrders: { min: 18, max: 80 },
    catalogSkuRange: [40, 520],
    channelSuitability: channels({
      meta: 0.95,
      google_shopping: 0.82,
      pinterest: 0.78,
      email: 0.82,
      sms: 0.52,
    }),
    aovBias: { medium: 1.5, high: 0.8 },
    frequencyBias: { occasional: 1.2, repeat: 1.4 },
    marketingBias: { paid_media_heavy: 1.25, balanced: 1.2 },
    promotionBias: {
      promotion_sensitive: 1.35,
      promotion_heavy: 1.15,
      clearance_heavy: 0.8,
    },
    catalogBias: { large: 1.5, very_large: 1.1, long_tail: 0.8 },
    inventoryBias: { stockout_prone: 1.1, long_lead_time: 0.9 },
    customerEconomicsBias: {
      acquisition_driven: 1.2,
      retention_driven: 1.0,
    },
    seasonalityBias: { strong: 1.2, q4_heavy: 1.1, holiday_heavy: 0.9 },
  },
  beauty_cosmetics: {
    aovMinor: { min: 3500, max: 14500 },
    grossMarginRate: { min: 0.58, max: 0.82 },
    repeatProbability: { min: 0.35, max: 0.72 },
    purchaseIntervalDays: { min: 25, max: 100 },
    unitsPerOrder: { min: 1.4, max: 3.2 },
    returnRate: { min: 0.02, max: 0.1 },
    shippingSubsidyRate: { min: 0.025, max: 0.09 },
    paymentFeeRate: { min: 0.022, max: 0.036 },
    fulfillmentRate: { min: 0.04, max: 0.1 },
    baselineConversionRate: { min: 0.018, max: 0.06 },
    considerationDays: { min: 1, max: 8 },
    brandStrength: { min: 0.08, max: 0.58 },
    organicStrength: { min: 0.1, max: 0.45 },
    visualAffinity: 0.9,
    searchIntent: 0.58,
    lifecycleAffinity: 0.88,
    priceSensitivity: { min: -1.9, max: -0.55 },
    inventoryLeadDays: { min: 10, max: 75 },
    inventoryDepthOrders: { min: 30, max: 130 },
    catalogSkuRange: [20, 260],
    channelSuitability: channels({
      meta: 0.94,
      google_shopping: 0.72,
      pinterest: 0.65,
      email: 0.94,
      sms: 0.62,
      affiliate: 0.55,
    }),
    aovBias: { low: 1.1, medium: 1.5 },
    frequencyBias: { repeat: 1.4, replenishment: 1.15 },
    marketingBias: { retention_heavy: 1.25, balanced: 1.15 },
    promotionBias: { light_promotion: 1.1, promotion_sensitive: 1.2 },
    catalogBias: { moderate: 1.25, large: 1.1 },
    inventoryBias: { replenishment_friendly: 1.35, deep: 1.05 },
    customerEconomicsBias: { retention_driven: 1.35, high_ltv: 1.2 },
    seasonalityBias: { moderate: 1.2, holiday_heavy: 0.85 },
  },
  furniture: {
    aovMinor: { min: 35000, max: 240000 },
    grossMarginRate: { min: 0.38, max: 0.62 },
    repeatProbability: { min: 0.06, max: 0.28 },
    purchaseIntervalDays: { min: 180, max: 900 },
    unitsPerOrder: { min: 1.0, max: 1.8 },
    returnRate: { min: 0.02, max: 0.11 },
    shippingSubsidyRate: { min: 0.045, max: 0.16 },
    paymentFeeRate: { min: 0.021, max: 0.035 },
    fulfillmentRate: { min: 0.055, max: 0.18 },
    baselineConversionRate: { min: 0.003, max: 0.018 },
    considerationDays: { min: 8, max: 60 },
    brandStrength: { min: 0.06, max: 0.48 },
    organicStrength: { min: 0.15, max: 0.55 },
    visualAffinity: 0.82,
    searchIntent: 0.8,
    lifecycleAffinity: 0.35,
    priceSensitivity: { min: -1.4, max: -0.35 },
    inventoryLeadDays: { min: 35, max: 210 },
    inventoryDepthOrders: { min: 4, max: 30 },
    catalogSkuRange: [18, 220],
    channelSuitability: channels({
      meta: 0.74,
      google_search: 0.9,
      google_shopping: 0.8,
      pinterest: 0.82,
      email: 0.5,
      sms: 0.18,
      affiliate: 0.2,
    }),
    aovBias: { high: 1.4, extreme: 1.2 },
    frequencyBias: { one_off: 1.45, infrequent: 1.25 },
    marketingBias: { organic_heavy: 1.1, balanced: 1.2 },
    promotionBias: { full_price_dominant: 1.05, light_promotion: 1.25 },
    catalogBias: { moderate: 1.25, large: 1.0 },
    inventoryBias: {
      long_lead_time: 1.4,
      shallow: 1.1,
      stockout_prone: 0.9,
    },
    customerEconomicsBias: { acquisition_driven: 1.15, low_repeat: 1.4 },
    seasonalityBias: { moderate: 1.25, q4_heavy: 0.8 },
  },
  home_furnishings_decor: {
    aovMinor: { min: 9000, max: 65000 },
    grossMarginRate: { min: 0.42, max: 0.68 },
    repeatProbability: { min: 0.12, max: 0.4 },
    purchaseIntervalDays: { min: 75, max: 360 },
    unitsPerOrder: { min: 1.1, max: 2.2 },
    returnRate: { min: 0.025, max: 0.14 },
    shippingSubsidyRate: { min: 0.035, max: 0.13 },
    paymentFeeRate: { min: 0.021, max: 0.036 },
    fulfillmentRate: { min: 0.045, max: 0.15 },
    baselineConversionRate: { min: 0.006, max: 0.028 },
    considerationDays: { min: 3, max: 30 },
    brandStrength: { min: 0.06, max: 0.5 },
    organicStrength: { min: 0.14, max: 0.58 },
    visualAffinity: 0.9,
    searchIntent: 0.72,
    lifecycleAffinity: 0.48,
    priceSensitivity: { min: -1.65, max: -0.45 },
    inventoryLeadDays: { min: 20, max: 150 },
    inventoryDepthOrders: { min: 7, max: 50 },
    catalogSkuRange: [30, 420],
    channelSuitability: channels({
      meta: 0.82,
      google_search: 0.82,
      google_shopping: 0.83,
      pinterest: 0.92,
      email: 0.62,
      sms: 0.25,
    }),
    aovBias: { medium: 1.15, high: 1.3 },
    frequencyBias: { infrequent: 1.2, occasional: 1.2 },
    marketingBias: { organic_heavy: 1.05, balanced: 1.3 },
    promotionBias: { light_promotion: 1.25, promotion_sensitive: 0.9 },
    catalogBias: { large: 1.2, very_large: 0.9, long_tail: 0.8 },
    inventoryBias: { long_lead_time: 1.1, shallow: 1.0 },
    customerEconomicsBias: { acquisition_driven: 1.1, low_repeat: 1.1 },
    seasonalityBias: { moderate: 1.2, q4_heavy: 0.95 },
  },
  supplements_wellness: {
    aovMinor: { min: 3500, max: 12000 },
    grossMarginRate: { min: 0.5, max: 0.78 },
    repeatProbability: { min: 0.42, max: 0.82 },
    purchaseIntervalDays: { min: 20, max: 70 },
    unitsPerOrder: { min: 1.2, max: 2.8 },
    returnRate: { min: 0.01, max: 0.06 },
    shippingSubsidyRate: { min: 0.02, max: 0.075 },
    paymentFeeRate: { min: 0.022, max: 0.037 },
    fulfillmentRate: { min: 0.035, max: 0.09 },
    baselineConversionRate: { min: 0.018, max: 0.065 },
    considerationDays: { min: 1, max: 10 },
    brandStrength: { min: 0.05, max: 0.45 },
    organicStrength: { min: 0.08, max: 0.4 },
    visualAffinity: 0.45,
    searchIntent: 0.72,
    lifecycleAffinity: 0.95,
    priceSensitivity: { min: -1.8, max: -0.5 },
    inventoryLeadDays: { min: 8, max: 55 },
    inventoryDepthOrders: { min: 45, max: 180 },
    catalogSkuRange: [8, 120],
    channelSuitability: channels({
      meta: 0.83,
      google_search: 0.85,
      google_shopping: 0.55,
      pinterest: 0.25,
      email: 0.96,
      sms: 0.72,
      affiliate: 0.62,
    }),
    aovBias: { low: 1.2, medium: 1.1 },
    frequencyBias: { replenishment: 1.5, subscription: 0.9, repeat: 1.1 },
    marketingBias: { retention_heavy: 1.45, paid_media_heavy: 0.9 },
    promotionBias: { light_promotion: 1.1, promotion_sensitive: 1.1 },
    catalogBias: { tiny_curated: 1.0, moderate: 1.4 },
    inventoryBias: { replenishment_friendly: 1.55, deep: 1.1 },
    customerEconomicsBias: { high_ltv: 1.25, retention_driven: 1.55 },
    seasonalityBias: { low: 1.3, moderate: 1.1 },
  },
  consumer_electronics: {
    aovMinor: { min: 9000, max: 90000 },
    grossMarginRate: { min: 0.18, max: 0.48 },
    repeatProbability: { min: 0.1, max: 0.34 },
    purchaseIntervalDays: { min: 120, max: 540 },
    unitsPerOrder: { min: 1.0, max: 1.7 },
    returnRate: { min: 0.04, max: 0.16 },
    shippingSubsidyRate: { min: 0.02, max: 0.085 },
    paymentFeeRate: { min: 0.02, max: 0.034 },
    fulfillmentRate: { min: 0.025, max: 0.09 },
    baselineConversionRate: { min: 0.006, max: 0.03 },
    considerationDays: { min: 2, max: 28 },
    brandStrength: { min: 0.04, max: 0.4 },
    organicStrength: { min: 0.15, max: 0.55 },
    visualAffinity: 0.35,
    searchIntent: 0.96,
    lifecycleAffinity: 0.4,
    priceSensitivity: { min: -2.4, max: -0.7 },
    inventoryLeadDays: { min: 10, max: 90 },
    inventoryDepthOrders: { min: 10, max: 60 },
    catalogSkuRange: [20, 350],
    channelSuitability: channels({
      meta: 0.45,
      google_search: 0.98,
      google_shopping: 0.96,
      pinterest: 0.12,
      email: 0.5,
      affiliate: 0.58,
    }),
    aovBias: { medium: 1.05, high: 1.25 },
    frequencyBias: { infrequent: 1.35, occasional: 0.8 },
    marketingBias: { organic_heavy: 1.05, paid_media_heavy: 1.1 },
    promotionBias: { promotion_sensitive: 1.2, promotion_heavy: 0.9 },
    catalogBias: { moderate: 1.1, large: 1.25 },
    inventoryBias: { short_lead_time: 1.05, stockout_prone: 0.8 },
    customerEconomicsBias: { acquisition_driven: 1.3, low_repeat: 1.15 },
    seasonalityBias: { q4_heavy: 1.25, holiday_heavy: 1.1 },
  },
  specialty_retail: {
    aovMinor: { min: 4500, max: 50000 },
    grossMarginRate: { min: 0.35, max: 0.7 },
    repeatProbability: { min: 0.15, max: 0.52 },
    purchaseIntervalDays: { min: 45, max: 360 },
    unitsPerOrder: { min: 1.0, max: 2.5 },
    returnRate: { min: 0.015, max: 0.14 },
    shippingSubsidyRate: { min: 0.02, max: 0.11 },
    paymentFeeRate: { min: 0.021, max: 0.036 },
    fulfillmentRate: { min: 0.03, max: 0.12 },
    baselineConversionRate: { min: 0.008, max: 0.045 },
    considerationDays: { min: 1, max: 24 },
    brandStrength: { min: 0.04, max: 0.5 },
    organicStrength: { min: 0.12, max: 0.58 },
    visualAffinity: 0.55,
    searchIntent: 0.72,
    lifecycleAffinity: 0.62,
    priceSensitivity: { min: -1.9, max: -0.45 },
    inventoryLeadDays: { min: 10, max: 110 },
    inventoryDepthOrders: { min: 12, max: 90 },
    catalogSkuRange: [15, 400],
    channelSuitability: channels({ google_search: 0.82, email: 0.72 }),
    aovBias: { medium: 1.2, high: 0.7 },
    frequencyBias: { occasional: 1.2, repeat: 0.9 },
    marketingBias: { balanced: 1.45, organic_heavy: 1.0 },
    promotionBias: { light_promotion: 1.25, full_price_dominant: 0.9 },
    catalogBias: { moderate: 1.2, large: 0.9 },
    inventoryBias: { deep: 1.0, short_lead_time: 1.0 },
    customerEconomicsBias: { acquisition_driven: 1.0, retention_driven: 1.0 },
    seasonalityBias: { moderate: 1.3, low: 0.8 },
  },
  luxury: {
    aovMinor: { min: 30000, max: 350000 },
    grossMarginRate: { min: 0.55, max: 0.85 },
    repeatProbability: { min: 0.08, max: 0.38 },
    purchaseIntervalDays: { min: 120, max: 720 },
    unitsPerOrder: { min: 1.0, max: 1.5 },
    returnRate: { min: 0.02, max: 0.12 },
    shippingSubsidyRate: { min: 0.025, max: 0.12 },
    paymentFeeRate: { min: 0.02, max: 0.034 },
    fulfillmentRate: { min: 0.04, max: 0.16 },
    baselineConversionRate: { min: 0.0025, max: 0.018 },
    considerationDays: { min: 5, max: 50 },
    brandStrength: { min: 0.16, max: 0.72 },
    organicStrength: { min: 0.2, max: 0.7 },
    visualAffinity: 0.84,
    searchIntent: 0.6,
    lifecycleAffinity: 0.48,
    priceSensitivity: { min: -0.9, max: -0.12 },
    inventoryLeadDays: { min: 25, max: 180 },
    inventoryDepthOrders: { min: 4, max: 35 },
    catalogSkuRange: [6, 140],
    channelSuitability: channels({
      meta: 0.72,
      google_search: 0.62,
      google_shopping: 0.42,
      pinterest: 0.68,
      email: 0.58,
      sms: 0.15,
      affiliate: 0.22,
    }),
    aovBias: { high: 1.15, extreme: 1.6 },
    frequencyBias: { one_off: 1.15, infrequent: 1.25 },
    marketingBias: { organic_heavy: 1.45, balanced: 0.8 },
    promotionBias: { full_price_dominant: 1.8, light_promotion: 0.7 },
    catalogBias: { tiny_curated: 1.45, moderate: 1.0 },
    inventoryBias: { shallow: 1.35, long_lead_time: 1.0 },
    customerEconomicsBias: { high_ltv: 1.2, low_repeat: 1.05 },
    seasonalityBias: { moderate: 1.0, holiday_heavy: 0.9, q4_heavy: 0.75 },
  },
  commodity_value_retail: {
    aovMinor: { min: 1800, max: 9000 },
    grossMarginRate: { min: 0.18, max: 0.45 },
    repeatProbability: { min: 0.2, max: 0.58 },
    purchaseIntervalDays: { min: 25, max: 160 },
    unitsPerOrder: { min: 1.5, max: 4.2 },
    returnRate: { min: 0.015, max: 0.1 },
    shippingSubsidyRate: { min: 0.025, max: 0.1 },
    paymentFeeRate: { min: 0.024, max: 0.04 },
    fulfillmentRate: { min: 0.05, max: 0.14 },
    baselineConversionRate: { min: 0.018, max: 0.075 },
    considerationDays: { min: 0.2, max: 5 },
    brandStrength: { min: 0.01, max: 0.22 },
    organicStrength: { min: 0.08, max: 0.38 },
    visualAffinity: 0.3,
    searchIntent: 0.78,
    lifecycleAffinity: 0.65,
    priceSensitivity: { min: -3.0, max: -1.0 },
    inventoryLeadDays: { min: 5, max: 65 },
    inventoryDepthOrders: { min: 40, max: 180 },
    catalogSkuRange: [40, 700],
    channelSuitability: channels({
      meta: 0.55,
      google_search: 0.82,
      google_shopping: 0.94,
      email: 0.7,
      sms: 0.4,
      affiliate: 0.42,
    }),
    aovBias: { very_low: 1.35, low: 1.5 },
    frequencyBias: { occasional: 1.1, repeat: 1.2 },
    marketingBias: { paid_media_heavy: 1.25, balanced: 1.0 },
    promotionBias: { promotion_heavy: 1.4, clearance_heavy: 1.2 },
    catalogBias: { large: 1.25, long_tail: 1.1 },
    inventoryBias: { deep: 1.25, replenishment_friendly: 1.0 },
    customerEconomicsBias: { acquisition_driven: 1.25, low_repeat: 0.75 },
    seasonalityBias: { moderate: 1.15, holiday_heavy: 0.9 },
  },
  replenishment_heavy: {
    aovMinor: { min: 2500, max: 12000 },
    grossMarginRate: { min: 0.42, max: 0.75 },
    repeatProbability: { min: 0.55, max: 0.88 },
    purchaseIntervalDays: { min: 14, max: 60 },
    unitsPerOrder: { min: 1.1, max: 2.8 },
    returnRate: { min: 0.005, max: 0.06 },
    shippingSubsidyRate: { min: 0.02, max: 0.08 },
    paymentFeeRate: { min: 0.023, max: 0.039 },
    fulfillmentRate: { min: 0.035, max: 0.1 },
    baselineConversionRate: { min: 0.02, max: 0.075 },
    considerationDays: { min: 0.2, max: 5 },
    brandStrength: { min: 0.05, max: 0.5 },
    organicStrength: { min: 0.08, max: 0.38 },
    visualAffinity: 0.42,
    searchIntent: 0.68,
    lifecycleAffinity: 0.98,
    priceSensitivity: { min: -1.8, max: -0.45 },
    inventoryLeadDays: { min: 5, max: 45 },
    inventoryDepthOrders: { min: 55, max: 220 },
    catalogSkuRange: [6, 100],
    channelSuitability: channels({
      meta: 0.78,
      google_search: 0.78,
      email: 0.99,
      sms: 0.8,
      affiliate: 0.45,
    }),
    aovBias: { low: 1.35, medium: 0.9 },
    frequencyBias: { replenishment: 1.8, repeat: 1.0 },
    marketingBias: { retention_heavy: 1.7, balanced: 0.7 },
    promotionBias: { light_promotion: 1.1, promotion_sensitive: 1.0 },
    catalogBias: { tiny_curated: 1.2, moderate: 1.25 },
    inventoryBias: { replenishment_friendly: 1.8, deep: 1.15 },
    customerEconomicsBias: { retention_driven: 1.6, high_ltv: 1.4 },
    seasonalityBias: { low: 1.55, moderate: 0.8 },
  },
  subscription_heavy: {
    aovMinor: { min: 2200, max: 16000 },
    grossMarginRate: { min: 0.45, max: 0.78 },
    repeatProbability: { min: 0.68, max: 0.94 },
    purchaseIntervalDays: { min: 20, max: 45 },
    unitsPerOrder: { min: 1.0, max: 2.3 },
    returnRate: { min: 0.005, max: 0.05 },
    shippingSubsidyRate: { min: 0.02, max: 0.075 },
    paymentFeeRate: { min: 0.023, max: 0.04 },
    fulfillmentRate: { min: 0.035, max: 0.095 },
    baselineConversionRate: { min: 0.015, max: 0.06 },
    considerationDays: { min: 0.5, max: 7 },
    brandStrength: { min: 0.07, max: 0.52 },
    organicStrength: { min: 0.07, max: 0.35 },
    visualAffinity: 0.45,
    searchIntent: 0.6,
    lifecycleAffinity: 1.0,
    priceSensitivity: { min: -1.6, max: -0.35 },
    inventoryLeadDays: { min: 5, max: 50 },
    inventoryDepthOrders: { min: 50, max: 220 },
    catalogSkuRange: [4, 80],
    channelSuitability: channels({
      meta: 0.8,
      google_search: 0.65,
      email: 1.0,
      sms: 0.85,
      affiliate: 0.5,
    }),
    aovBias: { low: 1.25, medium: 0.8 },
    frequencyBias: { subscription: 2.0, replenishment: 0.7 },
    marketingBias: { retention_heavy: 1.8, balanced: 0.6 },
    promotionBias: { light_promotion: 1.0, promotion_sensitive: 0.9 },
    catalogBias: { tiny_curated: 1.5, moderate: 1.0 },
    inventoryBias: { replenishment_friendly: 1.7, deep: 1.1 },
    customerEconomicsBias: { subscription: 1.9, high_ltv: 1.25 },
    seasonalityBias: { low: 1.65, moderate: 0.7 },
  },
};
