export const BASELINE_VALIDATION_SUITE_VERSION = "1.0.0" as const;
export const BASELINE_VALIDATION_CONTRACT_SCHEMA_VERSION = "1.0.0" as const;
export const BASELINE_CONFORMANCE_REPORT_SCHEMA_VERSION = "1.0.0" as const;

export const BASELINE_VALIDATION_FROZEN_PARENT_COMMIT =
  "3fbc5c9396f2471c7c6fdd5fb73b50cb107dcaf3" as const;
