import type { OpportunityDomain } from "./contract.js";

export interface OpportunityTemplate {
  readonly templateId: string;
  readonly areaCodes: readonly string[];
  readonly domain: OpportunityDomain;
  readonly title: string;
  readonly actionType: string;
  readonly targetKind: string;
  readonly parameterKeys: readonly string[];
  readonly requiredCapabilities: readonly string[];
  readonly primaryLever:
    | "TRAFFIC"
    | "CONVERSION"
    | "AOV"
    | "CAC"
    | "MARGIN"
    | "INVENTORY"
    | "REPEAT_RATE"
    | "RETENTION"
    | "RETURN_RATE"
    | "FULFILLMENT_COST"
    | "MEASUREMENT_QUALITY";
  readonly primaryMetric: string;
  readonly successDirection: "INCREASE" | "DECREASE" | "MAINTAIN" | "OBSERVE";
  readonly secondaryMetrics: readonly string[];
  readonly guardrailMetrics: readonly string[];
  readonly horizonDays: number;
  readonly effort: "LOW" | "MEDIUM" | "HIGH" | "UNKNOWN";
  readonly reversibility: "FULL" | "PARTIAL" | "NONE" | "UNKNOWN";
  readonly risk: "LOW" | "MEDIUM" | "HIGH" | "UNKNOWN";
  readonly consequenceApplicability: readonly (
    | "CANNIBALIZATION"
    | "CROSS_CHANNEL"
    | "INVENTORY"
    | "CUSTOMER"
    | "PROMOTION"
    | "OPERATIONAL"
  )[];
}

export const OPPORTUNITY_TEMPLATES: readonly OpportunityTemplate[] = [
  {
    templateId: "cro.checkout_fix",
    areaCodes: ["conversion_decline"],
    domain: "CRO",
    title: "Improve the checkout experience",
    actionType: "cro.modify_checkout",
    targetKind: "FUNNEL_STAGE",
    parameterKeys: ["change_ref"],
    requiredCapabilities: ["cro.modify_checkout"],
    primaryLever: "CONVERSION",
    primaryMetric: "cvr",
    successDirection: "INCREASE",
    secondaryMetrics: ["orders", "revenue_net"],
    guardrailMetrics: ["contribution_profit", "return_rate"],
    horizonDays: 14,
    effort: "MEDIUM",
    reversibility: "FULL",
    risk: "MEDIUM",
    consequenceApplicability: ["CUSTOMER", "OPERATIONAL"],
  },
  {
    templateId: "cro.checkout_experiment",
    areaCodes: ["conversion_decline"],
    domain: "CRO",
    title: "Run a checkout experiment",
    actionType: "experimentation.run_experiment",
    targetKind: "FUNNEL_STAGE",
    parameterKeys: ["experiment_ref"],
    requiredCapabilities: ["experimentation.run_experiment"],
    primaryLever: "CONVERSION",
    primaryMetric: "cvr",
    successDirection: "INCREASE",
    secondaryMetrics: ["orders"],
    guardrailMetrics: ["contribution_profit"],
    horizonDays: 21,
    effort: "MEDIUM",
    reversibility: "FULL",
    risk: "LOW",
    consequenceApplicability: ["CUSTOMER", "OPERATIONAL"],
  },
  {
    templateId: "acquisition.traffic_investigation",
    areaCodes: ["traffic_decline", "orders_decline", "revenue_decline"],
    domain: "INVESTIGATION",
    title: "Investigate acquisition quality and demand",
    actionType: "investigation.inspect",
    targetKind: "CHANNEL",
    parameterKeys: [],
    requiredCapabilities: ["investigation.inspect"],
    primaryLever: "MEASUREMENT_QUALITY",
    primaryMetric: "sessions",
    successDirection: "OBSERVE",
    secondaryMetrics: ["cvr", "orders", "revenue_net"],
    guardrailMetrics: [],
    horizonDays: 7,
    effort: "LOW",
    reversibility: "FULL",
    risk: "LOW",
    consequenceApplicability: [],
  },
  {
    templateId: "paid.reallocate_prospecting",
    areaCodes: ["retargeting_heavy", "paid_dependency_high", "new_customer_growth_weak"],
    domain: "PAID_MEDIA",
    title: "Reallocate paid media toward incremental acquisition",
    actionType: "advertising.set_allocation",
    targetKind: "CHANNEL",
    parameterKeys: ["prospecting_share_basis_points"],
    requiredCapabilities: ["advertising.set_allocation"],
    primaryLever: "CAC",
    primaryMetric: "cac",
    successDirection: "DECREASE",
    secondaryMetrics: ["new_customers", "incremental_paid_contribution"],
    guardrailMetrics: ["contribution_profit", "cvr"],
    horizonDays: 21,
    effort: "LOW",
    reversibility: "FULL",
    risk: "MEDIUM",
    consequenceApplicability: ["CANNIBALIZATION", "CROSS_CHANNEL", "CUSTOMER", "INVENTORY"],
  },
  {
    templateId: "paid.scale_incremental",
    areaCodes: ["traffic_decline", "product_momentum"],
    domain: "PAID_MEDIA",
    title: "Scale incremental paid acquisition",
    actionType: "advertising.adjust_budget",
    targetKind: "CAMPAIGN",
    parameterKeys: ["budget_delta_minor"],
    requiredCapabilities: ["advertising.adjust_budget"],
    primaryLever: "TRAFFIC",
    primaryMetric: "incremental_paid_contribution",
    successDirection: "INCREASE",
    secondaryMetrics: ["new_customers", "orders"],
    guardrailMetrics: ["cac", "contribution_profit", "inventory_days_cover_min"],
    horizonDays: 14,
    effort: "LOW",
    reversibility: "FULL",
    risk: "MEDIUM",
    consequenceApplicability: ["CANNIBALIZATION", "CROSS_CHANNEL", "INVENTORY", "CUSTOMER", "OPERATIONAL"],
  },
  {
    templateId: "merch.cross_sell",
    areaCodes: ["aov_decline", "product_momentum"],
    domain: "MERCHANDISING",
    title: "Improve cross-sell merchandising",
    actionType: "merchandising.set_cross_sell",
    targetKind: "PRODUCT",
    parameterKeys: ["related_product_ref"],
    requiredCapabilities: ["merchandising.set_cross_sell"],
    primaryLever: "AOV",
    primaryMetric: "aov",
    successDirection: "INCREASE",
    secondaryMetrics: ["revenue_net", "contribution_profit"],
    guardrailMetrics: ["cvr", "return_rate"],
    horizonDays: 21,
    effort: "LOW",
    reversibility: "FULL",
    risk: "LOW",
    consequenceApplicability: ["CANNIBALIZATION", "INVENTORY", "CUSTOMER"],
  },
  {
    templateId: "merch.feature_high_margin",
    areaCodes: ["margin_compression", "product_momentum", "inventory_at_risk"],
    domain: "MERCHANDISING",
    title: "Feature economically attractive products",
    actionType: "merchandising.feature",
    targetKind: "PRODUCT",
    parameterKeys: ["placement_ref"],
    requiredCapabilities: ["merchandising.feature"],
    primaryLever: "MARGIN",
    primaryMetric: "contribution_profit",
    successDirection: "INCREASE",
    secondaryMetrics: ["average_product_margin", "revenue_net"],
    guardrailMetrics: ["cvr", "inventory_days_cover_min"],
    horizonDays: 21,
    effort: "LOW",
    reversibility: "FULL",
    risk: "LOW",
    consequenceApplicability: ["CANNIBALIZATION", "INVENTORY", "CUSTOMER"],
  },
  {
    templateId: "promotion.reduce_discount",
    areaCodes: ["discount_driven_growth", "margin_compression"],
    domain: "PROMOTION",
    title: "Reduce promotion depth or scope",
    actionType: "promotion.modify",
    targetKind: "PROMOTION",
    parameterKeys: ["discount_basis_points"],
    requiredCapabilities: ["promotion.modify"],
    primaryLever: "MARGIN",
    primaryMetric: "contribution_profit",
    successDirection: "INCREASE",
    secondaryMetrics: ["discount_rate", "gross_margin"],
    guardrailMetrics: ["orders", "cvr", "retention_rate_90d"],
    horizonDays: 30,
    effort: "LOW",
    reversibility: "FULL",
    risk: "MEDIUM",
    consequenceApplicability: ["CANNIBALIZATION", "CUSTOMER", "PROMOTION", "INVENTORY"],
  },
  {
    templateId: "pricing.test_price",
    areaCodes: ["margin_compression", "discount_driven_growth"],
    domain: "PRICING",
    title: "Test a targeted price change",
    actionType: "pricing.adjust_price",
    targetKind: "SKU",
    parameterKeys: ["price_change_basis_points"],
    requiredCapabilities: ["pricing.adjust_price"],
    primaryLever: "MARGIN",
    primaryMetric: "contribution_profit",
    successDirection: "INCREASE",
    secondaryMetrics: ["gross_margin", "revenue_net"],
    guardrailMetrics: ["cvr", "orders", "return_rate"],
    horizonDays: 30,
    effort: "MEDIUM",
    reversibility: "FULL",
    risk: "MEDIUM",
    consequenceApplicability: ["CANNIBALIZATION", "CUSTOMER", "PROMOTION", "INVENTORY"],
  },
  {
    templateId: "inventory.reorder",
    areaCodes: ["inventory_constrained", "product_momentum"],
    domain: "INVENTORY",
    title: "Replenish constrained inventory",
    actionType: "inventory.reorder",
    targetKind: "SKU",
    parameterKeys: ["quantity"],
    requiredCapabilities: ["inventory.reorder"],
    primaryLever: "INVENTORY",
    primaryMetric: "inventory_days_cover_min",
    successDirection: "INCREASE",
    secondaryMetrics: ["out_of_stock_rate", "revenue_net"],
    guardrailMetrics: ["contribution_profit", "inventory_at_risk_value"],
    horizonDays: 30,
    effort: "MEDIUM",
    reversibility: "PARTIAL",
    risk: "MEDIUM",
    consequenceApplicability: ["INVENTORY", "OPERATIONAL"],
  },
  {
    templateId: "inventory.protect",
    areaCodes: ["inventory_constrained"],
    domain: "INVENTORY",
    title: "Protect scarce inventory from inefficient demand",
    actionType: "inventory.protect_inventory",
    targetKind: "SKU",
    parameterKeys: ["protection_policy_ref"],
    requiredCapabilities: ["inventory.protect_inventory"],
    primaryLever: "INVENTORY",
    primaryMetric: "inventory_days_cover_min",
    successDirection: "INCREASE",
    secondaryMetrics: ["contribution_profit"],
    guardrailMetrics: ["revenue_net"],
    horizonDays: 14,
    effort: "LOW",
    reversibility: "FULL",
    risk: "LOW",
    consequenceApplicability: ["INVENTORY", "CUSTOMER"],
  },
  {
    templateId: "inventory.accelerate_excess",
    areaCodes: ["inventory_at_risk"],
    domain: "INVENTORY",
    title: "Accelerate excess inventory",
    actionType: "inventory.accelerate_excess_stock",
    targetKind: "SKU",
    parameterKeys: ["clearance_strategy_ref"],
    requiredCapabilities: ["inventory.accelerate_excess_stock"],
    primaryLever: "INVENTORY",
    primaryMetric: "inventory_at_risk_value",
    successDirection: "DECREASE",
    secondaryMetrics: ["contribution_profit"],
    guardrailMetrics: ["gross_margin", "discount_rate"],
    horizonDays: 30,
    effort: "LOW",
    reversibility: "PARTIAL",
    risk: "MEDIUM",
    consequenceApplicability: ["CANNIBALIZATION", "INVENTORY", "PROMOTION", "CUSTOMER"],
  },
  {
    templateId: "lifecycle.winback",
    areaCodes: ["retention_weak", "lifecycle_underused"],
    domain: "RETENTION",
    title: "Activate a win-back lifecycle flow",
    actionType: "lifecycle.start_flow",
    targetKind: "CUSTOMER_SEGMENT",
    parameterKeys: ["flow_ref"],
    requiredCapabilities: ["lifecycle.start_flow"],
    primaryLever: "RETENTION",
    primaryMetric: "retention_rate_90d",
    successDirection: "INCREASE",
    secondaryMetrics: ["repeat_rate", "customer_value_90d"],
    guardrailMetrics: ["contribution_profit"],
    horizonDays: 60,
    effort: "MEDIUM",
    reversibility: "FULL",
    risk: "LOW",
    consequenceApplicability: ["CUSTOMER", "CROSS_CHANNEL", "OPERATIONAL"],
  },
  {
    templateId: "lifecycle.post_purchase",
    areaCodes: ["retention_weak", "lifecycle_underused"],
    domain: "LIFECYCLE",
    title: "Improve post-purchase lifecycle coverage",
    actionType: "lifecycle.modify_flow",
    targetKind: "LIFECYCLE_FLOW",
    parameterKeys: ["flow_change_ref"],
    requiredCapabilities: ["lifecycle.modify_flow"],
    primaryLever: "REPEAT_RATE",
    primaryMetric: "repeat_rate",
    successDirection: "INCREASE",
    secondaryMetrics: ["retention_rate_90d", "customer_value_90d"],
    guardrailMetrics: ["contribution_profit"],
    horizonDays: 60,
    effort: "MEDIUM",
    reversibility: "FULL",
    risk: "LOW",
    consequenceApplicability: ["CUSTOMER", "CROSS_CHANNEL", "OPERATIONAL"],
  },
  {
    templateId: "shipping.optimize_cost",
    areaCodes: ["shipping_cost_pressure"],
    domain: "SHIPPING",
    title: "Improve shipping economics",
    actionType: "shipping.adjust_policy",
    targetKind: "SHIPPING_POLICY",
    parameterKeys: ["policy_change_ref"],
    requiredCapabilities: ["shipping.adjust_policy"],
    primaryLever: "FULFILLMENT_COST",
    primaryMetric: "shipping_fulfillment_cost",
    successDirection: "DECREASE",
    secondaryMetrics: ["contribution_profit"],
    guardrailMetrics: ["cvr", "aov"],
    horizonDays: 30,
    effort: "MEDIUM",
    reversibility: "FULL",
    risk: "MEDIUM",
    consequenceApplicability: ["CUSTOMER", "OPERATIONAL"],
  },
  {
    templateId: "operational.returns",
    areaCodes: ["return_pressure"],
    domain: "OPERATIONAL",
    title: "Address return-related operating drag",
    actionType: "operational.change_setting",
    targetKind: "RESOURCE",
    parameterKeys: ["setting_ref", "value_ref"],
    requiredCapabilities: ["operational.change_setting"],
    primaryLever: "RETURN_RATE",
    primaryMetric: "return_rate",
    successDirection: "DECREASE",
    secondaryMetrics: ["returns_cost", "contribution_profit"],
    guardrailMetrics: ["cvr"],
    horizonDays: 30,
    effort: "MEDIUM",
    reversibility: "PARTIAL",
    risk: "MEDIUM",
    consequenceApplicability: ["CUSTOMER", "OPERATIONAL"],
  },
  {
    templateId: "investigation.measurement",
    areaCodes: ["measurement_gap", "measurement_confidence_low", "platform_roas_unverified"],
    domain: "INVESTIGATION",
    title: "Resolve measurement uncertainty before acting",
    actionType: "investigation.inspect",
    targetKind: "MERCHANT",
    parameterKeys: [],
    requiredCapabilities: ["investigation.inspect"],
    primaryLever: "MEASUREMENT_QUALITY",
    primaryMetric: "attribution_quality",
    successDirection: "INCREASE",
    secondaryMetrics: ["journey_coverage", "incrementality_measured_rate"],
    guardrailMetrics: [],
    horizonDays: 7,
    effort: "LOW",
    reversibility: "FULL",
    risk: "LOW",
    consequenceApplicability: [],
  },
];

export function templatesForArea(code: string): readonly OpportunityTemplate[] {
  return OPPORTUNITY_TEMPLATES.filter((template) => template.areaCodes.includes(code));
}

export function templateDomains(): ReadonlySet<OpportunityDomain> {
  return new Set(OPPORTUNITY_TEMPLATES.map((template) => template.domain));
}
